### ISSUE TITLE
Issues running your code

### ISSUE THREAD

**Issue by vsokolovliris** [jiangzhongshi/SurfaceNetworks#6]
Hello,

First, thank your for publishing your code here :)

I would like to run the neural network to test it, and try to adapt it to what I want to do.

I succeded to preprocess the data, by running add_laplacian.py on my meshes.

But now, I don't understand what to do next. I didn't find any documentation about it, except the first readme.

I tried to run train_4_normals.py, but I have issues for missing modules : 

```
ModuleNotFoundError: No module named 'pyigl'
``` 

It seems it is related to what you wrote in the Readme :
(optional)Python bindings for libigl is used for geometry processing. It's not required for reproducing the experiment, but if you would like to recompute Laplacian, Dirac etc, it would be convenient to install through pip install git+https://github.com/jiangzhongshi/libigl@cluster-pyigl#egg=pyigl

However, this command doesn't work anymore, it can't find the correct branch.

Can you help me a bit, by telling what I'm doing wrong, or what I have to do ?

Best Regards,
Vlad

**Comment by jiangzhongshi** [comment]
Hi,

In order to reproduce some experiments from the paper, please run https://github.com/jiangzhongshi/SurfaceNetworks/blob/dev/src/as_rigid_as_possible/main.py

The train normals is another test, so it made use of some customized locally code. I apologize for that, with the most recent commit, it should work after installing `conda install -c conda-forge igl`


Please let me know if there are still any problems.

Thanks,
Zhongshi

**Comment by vsokolovliris** [comment]
Hi,
I fixed manually the issue I have with pyigl and iglhelpers, I have no more errors now. 
Thanks for telling me where to start to reproduce the experiments.

This issue can be closed, thanks again.
Best regards,
Vlad
